/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Patient;
import Business.Organization.PatientOrganization;
import Business.Organization.SupplierOrganization;
import Business.Patient.Patient;
import Business.Person.Person;
import Business.Prescription.Diagnosis;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class DoctorWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private Person doctor;

    /**
     * Creates new form DoctorWorkAreaPanel
     */
    public DoctorWorkAreaPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        doctor = userAccount.getPerson();
        populatePatientComboBox();
        lblDoctorName.setText(userAccount.getUsername());
        lblNetworkName.setText(network.getName());
    }

    public void populatePatientComboBox() {
        patientCombo.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof PatientOrganization) {
                for (Person p : organization.getPersonDirectory().getPersonList()) {

                    Patient patient = (Patient) p;

                    patientCombo.addItem(patient);
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNetworkName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patientCombo = new javax.swing.JComboBox();
        providePrescription = new javax.swing.JButton();
        btnShowDiagnosis = new javax.swing.JButton();
        btnProvidePrescription = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Doctor name:");
        add(jLabel1);
        jLabel1.setBounds(90, 140, 130, 30);

        lblDoctorName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDoctorName.setText("jLabel2");
        add(lblDoctorName);
        lblDoctorName.setBounds(260, 140, 130, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Network name:");
        add(jLabel2);
        jLabel2.setBounds(550, 150, 140, 19);

        lblNetworkName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNetworkName.setText("jLabel3");
        add(lblNetworkName);
        lblNetworkName.setBounds(740, 150, 120, 19);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Select Patient:");
        add(jLabel4);
        jLabel4.setBounds(90, 240, 130, 19);

        patientCombo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(patientCombo);
        patientCombo.setBounds(280, 230, 165, 37);

        providePrescription.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        providePrescription.setText("Provide Prescription");
        providePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providePrescriptionActionPerformed(evt);
            }
        });
        add(providePrescription);
        providePrescription.setBounds(530, 230, 310, 40);

        btnShowDiagnosis.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnShowDiagnosis.setText("Show Diagnosis History");
        btnShowDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDiagnosisActionPerformed(evt);
            }
        });
        add(btnShowDiagnosis);
        btnShowDiagnosis.setBounds(530, 300, 310, 40);

        btnProvidePrescription.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnProvidePrescription.setText("Prescription Tracking details");
        btnProvidePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvidePrescriptionActionPerformed(evt);
            }
        });
        add(btnProvidePrescription);
        btnProvidePrescription.setBounds(530, 370, 310, 41);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Doctor Work Area JPanel");
        add(jLabel5);
        jLabel5.setBounds(400, 50, 320, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 2000, 960);
    }// </editor-fold>//GEN-END:initComponents

    private void providePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providePrescriptionActionPerformed
        // TODO add your handling code here:
        Patient patient = (Patient) patientCombo.getSelectedItem();
        AddPrescriptionJPanel addPresJPanel = new AddPrescriptionJPanel(userProcessContainer, userAccount, enterprise, network, doctor, patient);
        userProcessContainer.add("addPresJPanel", addPresJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_providePrescriptionActionPerformed

    private void btnShowDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDiagnosisActionPerformed
        // TODO add your handling code here:
        Patient patient = (Patient) patientCombo.getSelectedItem();
        ShowDiagnosisHistoryJPanel showDiagnosisHistoryJPanel = new ShowDiagnosisHistoryJPanel(userProcessContainer, patient);
        userProcessContainer.add("showDiagnosisHistoryJPanel", showDiagnosisHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnShowDiagnosisActionPerformed

    private void btnProvidePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvidePrescriptionActionPerformed
        // TODO add your handling code here:
        Patient patient = (Patient) patientCombo.getSelectedItem();
        ViewPrescriptionTrackJPanel viewPrescriptionTrack = new ViewPrescriptionTrackJPanel(userProcessContainer, patient);
        userProcessContainer.add("viewPrescriptionTrack", viewPrescriptionTrack);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnProvidePrescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProvidePrescription;
    private javax.swing.JButton btnShowDiagnosis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JComboBox patientCombo;
    private javax.swing.JButton providePrescription;
    // End of variables declaration//GEN-END:variables

}
