/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.SendInvoiceinEmail;
import Business.CreatePDF;
import Business.Drug.DrugItem;
import Business.Patient.Patient;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class GenerateBillJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    private ArrayList<DrugItem> drugItemList;
    private Pattern pattern;
    private Matcher matcher;
    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    private double total;

    /**
     * Creates new form GenerateBillJPanel
     */
    public GenerateBillJPanel(JPanel userProcessContainer, Patient patient, ArrayList<DrugItem> drugItemList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.drugItemList = drugItemList;
        pattern = Pattern.compile(EMAIL_PATTERN);
        lblPatientName.setText(patient.getFirstName() + " " + patient.getLastName());
        populateInvoice();
        populateTotalAmount(drugItemList);

    }

    private void populateTotalAmount(ArrayList<DrugItem> drugItemList) {
        total = 0;
        for (DrugItem di : drugItemList) {
            total = total + di.getDrug().getPrice() * di.getQuantity();
        }
        lblTotalAmount.setText("$" + String.valueOf(total));

    }

    public void populateInvoice() {
        DefaultTableModel dtm = (DefaultTableModel) tblInvoice.getModel();
        dtm.setRowCount(0);

        for (DrugItem drugItem : drugItemList) {
            Object row[] = new Object[5];
            row[0] = drugItem.getDrug();
            row[1] = drugItem.getDrug().getDrugName();
            row[2] = drugItem.getDrug().getPrice();
            row[3] = drugItem.getQuantity();
            row[4] = drugItem.getDrug().getPrice() * drugItem.getQuantity();

            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        btnCreatePDF = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        txtEmailAddress = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Generate Invoice");
        add(jLabel1);
        jLabel1.setBounds(460, 30, 250, 31);

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Single Unit Price", "Quantity", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInvoice);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 766, 209);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Patient Name:");
        add(jLabel2);
        jLabel2.setBounds(60, 80, 96, 19);

        lblPatientName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPatientName.setText("<<>>");
        add(lblPatientName);
        lblPatientName.setBounds(190, 80, 250, 19);

        btnCreatePDF.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCreatePDF.setText("Create PDF");
        btnCreatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePDFActionPerformed(evt);
            }
        });
        add(btnCreatePDF);
        btnCreatePDF.setBounds(60, 420, 140, 40);

        btnSendEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSendEmail.setText("Send Email");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });
        add(btnSendEmail);
        btnSendEmail.setBounds(640, 410, 190, 40);

        txtEmailAddress.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        add(txtEmailAddress);
        txtEmailAddress.setBounds(360, 410, 250, 40);

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(64, 29, 90, 31);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Total amount:");
        add(jLabel4);
        jLabel4.setBounds(510, 360, 160, 19);

        lblTotalAmount.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTotalAmount.setText("<<>>");
        add(lblTotalAmount);
        lblTotalAmount.setBounds(680, 360, 90, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1980, 970);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePDFActionPerformed
        // TODO add your handling code here:
        CreatePDF createPDF = new CreatePDF();
        createPDF.createPDFfromInvoice(drugItemList, patient, total);
        JOptionPane.showMessageDialog(null, "Invoice bill generated in PDF");


    }//GEN-LAST:event_btnCreatePDFActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:

        String emailAddress = "";

        if (!txtEmailAddress.equals("")) {
            String txt = txtEmailAddress.getText();
            if (txt.matches(EMAIL_PATTERN)) {
                JOptionPane.showMessageDialog(null, "Valid Email Id");
                emailAddress = txt;
            } else {

                JOptionPane.showMessageDialog(null, "Invalid Id");
                return;
            }

        } else if (!(patient.getEmailAddress().equals(""))) {
            emailAddress = patient.getEmailAddress();
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid email Id");
            return;
        }
        /*   
        
         if (!(patient.getEmailAddress().equals(""))) {
         emailAddress = patient.getEmailAddress();
         } else {

         if (!txtEmailAddress.equals("")) {
         String txt = txtEmailAddress.getText();
         if (txt.matches(EMAIL_PATTERN)) {
         JOptionPane.showMessageDialog(null, "Valid Email Id");
         emailAddress = txt;
         } else {

         JOptionPane.showMessageDialog(null, "Invalid Id");
         return;
         }
         } else {
         JOptionPane.showMessageDialog(null, "Please enter an email Id in the text Box.");
         return;
         }
         }
         */
        SendInvoiceinEmail send = new SendInvoiceinEmail();
        try {
            send.sendEmail(emailAddress);
        } catch (MessagingException ex) {
            Logger.getLogger(GenerateBillJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Invoice emailed succesfully!!!");
    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    public void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDrugWorkRequest manageDrugWorkRequest = (ManageDrugWorkRequest) component;
        manageDrugWorkRequest.populateDrugRequest();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePDF;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtEmailAddress;
    // End of variables declaration//GEN-END:variables

}
