/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.Drug.DrugInventory;
import Business.Drug.DrugItem;
import Business.Organization.PharmacyOrganization;
import Business.WorkQueue.AddInventoryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class ManageSupplierWorkRequest extends javax.swing.JPanel {

    private PharmacyOrganization pharmacyOrganization;
    private JPanel userProcessContainer;
    private DrugInventory drugInventory;

    /**
     * Creates new form ManageSupplierWorkRequest
     */
    public ManageSupplierWorkRequest(DrugInventory drugInventory, PharmacyOrganization pharmacyOrganization, JPanel userProcessContainer) {
        initComponents();
        this.drugInventory = drugInventory;
        this.pharmacyOrganization = pharmacyOrganization;
        this.userProcessContainer = userProcessContainer;
        populateDrugRequest();
    }

    public void populateDrugRequest() {

        DefaultTableModel model = (DefaultTableModel) tblWorkRequest.getModel();

        model.setRowCount(0);

        for (WorkRequest request : pharmacyOrganization.getWorkQueue().getWorkRequestList()) {

            if (request instanceof AddInventoryWorkRequest) {
                Object[] row = new Object[7];
                row[0] = request;
                row[1] = request.getSender().getPerson().getFirstName();
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getPerson().getFirstName();
                row[3] = request.getRequestDate();
                row[4] = request.getResolveDate();
                row[5] = request.getMessage();
                row[6] = request.getStatus();

                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnClosedRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnShowQuantity = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugItem = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Manage Supplier Work Request");
        add(jLabel1);
        jLabel1.setBounds(410, 40, 364, 31);

        tblWorkRequest.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request", "Sender", "Receiver", "Request Date", "Response Date", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);
        if (tblWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblWorkRequest.getColumnModel().getColumn(0).setMinWidth(0);
            tblWorkRequest.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblWorkRequest.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(88, 103, 960, 206);

        btnClosedRequest.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnClosedRequest.setText("Mark request as closed");
        btnClosedRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedRequestActionPerformed(evt);
            }
        });
        add(btnClosedRequest);
        btnClosedRequest.setBounds(590, 343, 254, 40);

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(90, 40, 80, 31);

        btnShowQuantity.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnShowQuantity.setText("Show Quantity ");
        btnShowQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowQuantityActionPerformed(evt);
            }
        });
        add(btnShowQuantity);
        btnShowQuantity.setBounds(88, 343, 213, 40);

        tblDrugItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Quantity Requested"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDrugItem);

        add(jScrollPane2);
        jScrollPane2.setBounds(88, 454, 514, 165);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1940, 1020);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClosedRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedRequestActionPerformed
        // TODO add your handling code here:
        int row = tblWorkRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select an entry form the table", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        AddInventoryWorkRequest aiwr = (AddInventoryWorkRequest) tblWorkRequest.getValueAt(row, 0);
        if (aiwr.getStatus().equals("Closed")) {
            JOptionPane.showMessageDialog(null, "This request has already been closed");
            return;
        }
        
        if(aiwr.getStatus().equals("Completed"))
        {
        aiwr.setStatus("Closed");
        JOptionPane.showMessageDialog(null, "The request has been closed succesfully");

        JOptionPane.showMessageDialog(null, "Updating inventory");

        ArrayList<DrugItem> drugItemList = aiwr.getDrugItemList();

        updateInventory(drugItemList);
        populateDrugRequest();

        }
        else
        {
        JOptionPane.showMessageDialog(null, "The request has not yet been completed");
        return;
        }
    }//GEN-LAST:event_btnClosedRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShowQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQuantityActionPerformed
        // TODO add your handling code here:

        int row = tblWorkRequest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select an entry form the table", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        AddInventoryWorkRequest aiwr = (AddInventoryWorkRequest) tblWorkRequest.getValueAt(row, 0);

        DefaultTableModel dtm = (DefaultTableModel) tblDrugItem.getModel();
        dtm.setRowCount(0);
        for (DrugItem drugItem : aiwr.getDrugItemList()) {

            Object r[] = new Object[3];
            r[0] = drugItem.getDrug().getDrugId();
            r[1] = drugItem.getDrug().getDrugName();
            r[2] = drugItem.getQuantity();
            dtm.addRow(r);

        }


    }//GEN-LAST:event_btnShowQuantityActionPerformed

    public void backAction() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }

    private void updateInventory(ArrayList<DrugItem> drugItemList) {

        boolean found = false;
        for (DrugItem drugItem : drugItemList) {
            found = false;
            for (DrugItem di : drugInventory.getDrugInventory()) {
                if (drugItem.getDrug() == di.getDrug()) {
                    found = true;
                    di.setQuantity(di.getQuantity() + drugItem.getQuantity());
                    JOptionPane.showMessageDialog(null, "Inventory has been added");
                    break;
                }
            }
            if (!found) {
                System.out.println("Not Found");
                drugInventory.getDrugInventory().add(drugItem);
                found = false;
            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClosedRequest;
    private javax.swing.JButton btnShowQuantity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDrugItem;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables

}
