/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.PharmacyRole;

import Business.Drug.DrugInventory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class PharmacistWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PharmacyOrganization pharmacyOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private DrugInventory drugInventory;
    

    /** Creates new form PharmacistWorkAreaJPanel */
    public PharmacistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Organization organization,  Enterprise enterprise, Network network,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.pharmacyOrganization = (PharmacyOrganization)organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        drugInventory = pharmacyOrganization.getDrugInventory();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageCatalog = new javax.swing.JButton();
        btnManageDrugRequest = new javax.swing.JButton();
        btnSupplierRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Pharmacist Work Area");
        add(jLabel1);
        jLabel1.setBounds(430, 50, 290, 31);

        btnManageCatalog.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnManageCatalog.setText("Manage Drug Catalog");
        btnManageCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCatalogActionPerformed(evt);
            }
        });
        add(btnManageCatalog);
        btnManageCatalog.setBounds(360, 150, 420, 50);

        btnManageDrugRequest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnManageDrugRequest.setText("Manage Drug Work Request to Customer");
        btnManageDrugRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugRequestActionPerformed(evt);
            }
        });
        add(btnManageDrugRequest);
        btnManageDrugRequest.setBounds(360, 260, 420, 60);

        btnSupplierRequest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSupplierRequest.setText("Manage Request to Supplier");
        btnSupplierRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierRequestActionPerformed(evt);
            }
        });
        add(btnSupplierRequest);
        btnSupplierRequest.setBounds(360, 370, 420, 47);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1930, 940);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCatalogActionPerformed
        // TODO add your handling code here:
        ManageDrugCatalogJPanel manageDrugCatalog = new ManageDrugCatalogJPanel(drugInventory,userAccount,pharmacyOrganization, enterprise,network, userProcessContainer);
        userProcessContainer.add("manageDrugCatalog", manageDrugCatalog);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCatalogActionPerformed

    private void btnManageDrugRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugRequestActionPerformed
        // TODO add your handling code here:
        ManageDrugWorkRequest manageDrugWorkRequest = new ManageDrugWorkRequest(userAccount,pharmacyOrganization, userProcessContainer);
        userProcessContainer.add("manageDrugWorkRequest", manageDrugWorkRequest);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnManageDrugRequestActionPerformed

    private void btnSupplierRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierRequestActionPerformed
        // TODO add your handling code here:
        ManageSupplierWorkRequest manageSupplierWorkRequest = new ManageSupplierWorkRequest(drugInventory,pharmacyOrganization, userProcessContainer);
        userProcessContainer.add("manageSupplierWorkRequest", manageSupplierWorkRequest);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnSupplierRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCatalog;
    private javax.swing.JButton btnManageDrugRequest;
    private javax.swing.JButton btnSupplierRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
