/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyRole;

import Business.Prescription.DrugDosages;
import Business.Prescription.Prescription;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class ShowPrescriptionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Prescription prescription;
    private UserAccount patientAccount;
    private SimpleDateFormat displayFormat;

    /**
     * Creates new form ShowPrescriptionJPanel
     */
    public ShowPrescriptionJPanel(JPanel userProcessContainer, Prescription prescription, UserAccount patientAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.prescription = prescription;
        this.patientAccount = patientAccount;
        displayFormat = new SimpleDateFormat("EEE, MMM d, ''yy");
        populatePrescription();

    }

    public void populatePrescription() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugDosage.getModel();
        dtm.setRowCount(0);

        for (DrugDosages dd : prescription.getDrugDosagesList()) {
            Object row[] = new Object[8];
            row[0] = dd.getDrug().getDrugId();
            row[1] = dd.getDrug().getDrugName();
            row[2] = dd.getFrequency().getMorning();
            row[3] = dd.getFrequency().getAfternoon();
            row[4] = dd.getFrequency().getEvening();
            row[5] = dd.getFrequency().getNight();
            row[6] = displayFormat.format(dd.getStartDate());
            row[7] = dd.getNoOfDays();

            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugDosage = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Show Prescription");
        add(jLabel1);
        jLabel1.setBounds(440, 50, 230, 31);

        tblDrugDosage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Morning", "Afternoon", "Evening", "Night", "Start Date", "No of days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugDosage);

        add(jScrollPane1);
        jScrollPane1.setBounds(64, 121, 856, 320);

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(64, 50, 90, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 2000, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrugDosage;
    // End of variables declaration//GEN-END:variables

}
