/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Drug.Drug;
import Business.Drug.DrugItem;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Prescription.DrugContents;
import Business.Prescription.DrugDosages;
import Business.Prescription.DrugItems;
import Business.Prescription.Prescription;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddDrugWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class BuyDrugsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private Patient patient;
    private DrugContents drugContents;
    private DefaultTableModel dtmWishList;
    private AddDrugWorkRequest addDrugWorkRequest;
    private Prescription prescription;
    private ArrayList<DrugItem> drugItemList;

    /**
     * Creates new form BuyDrugsJPanel
     */
    public BuyDrugsJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, Prescription prescription, AddDrugWorkRequest addDrugWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.addDrugWorkRequest = addDrugWorkRequest;
        this.prescription = prescription;
        drugItemList = new ArrayList<>();

        patient = (Patient) userAccount.getPerson();
        drugContents = patient.getDrugContents();

        dtmWishList = (DefaultTableModel) requestTable.getModel();
        dtmWishList.setRowCount(0);

        populateDrugContents();
        populatePharmaComboBox();
    }

    public void populatePharmaComboBox() {
        pharmacyJComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof PharmacyEnterprise) {

                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    pharmacyJComboBox.addItem(organization);

                }

            }
        }

    }

    public void populateDrugContents() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugContents.getModel();
        dtm.setRowCount(0);

        for (DrugItems di : drugContents.getDrugItemList()) {

            if (di.getDrugItem() != null) {
                Object row[] = new Object[4];
                row[0] = di.getDrugItem().getDrug();
                row[1] = di.getDrugItem().getDrug().getDrugName();
                row[2] = di.getQuantity();
                row[3] = di.getTotalQuantity();
                dtm.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugContents = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        pharmacyJComboBox = new javax.swing.JComboBox();
        btnRequestDrugs = new javax.swing.JButton();
        btnWishList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Drug contents:");
        add(jLabel1);
        jLabel1.setBounds(43, 79, 117, 16);

        tblDrugContents.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblDrugContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Dosage", "Drug Id", "No. of quantities", "total volume"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugContents);
        if (tblDrugContents.getColumnModel().getColumnCount() > 0) {
            tblDrugContents.getColumnModel().getColumn(0).setMinWidth(0);
            tblDrugContents.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblDrugContents.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(43, 113, 630, 174);

        requestTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Dosages", "Drug Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(0).setMinWidth(0);
            requestTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            requestTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(43, 353, 635, 194);

        pharmacyJComboBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(pharmacyJComboBox);
        pharmacyJComboBox.setBounds(715, 353, 290, 37);

        btnRequestDrugs.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRequestDrugs.setText("Request from Pharmacist");
        btnRequestDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestDrugsActionPerformed(evt);
            }
        });
        add(btnRequestDrugs);
        btnRequestDrugs.setBounds(715, 417, 290, 40);

        btnWishList.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnWishList.setText("Add to WishList");
        btnWishList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWishListActionPerformed(evt);
            }
        });
        add(btnWishList);
        btnWishList.setBounds(43, 300, 187, 35);

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(43, 34, 100, 31);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Buy Drugs");
        add(jLabel2);
        jLabel2.setBounds(530, 20, 130, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1960, 970);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWishListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWishListActionPerformed
        // TODO add your handling code here:
        int row = tblDrugContents.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select an entry form the table", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Drug drug = (Drug) tblDrugContents.getValueAt(row, 0);
        Object r[] = new Object[2];
        r[0] = drug;
        r[1] = drug.getDrugName();
        dtmWishList.addRow(r);

        DrugItem drugItem = new DrugItem();
        drugItem.setDrug(drug);
        drugItemList.add(drugItem);
        System.out.println("Drug added " + drugItem.getDrug());
    }//GEN-LAST:event_btnWishListActionPerformed

    private void btnRequestDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDrugsActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) pharmacyJComboBox.getSelectedItem();
        organization.getWorkQueue().getWorkRequestList().add(addDrugWorkRequest);
        userAccount.getWorkQueue().getWorkRequestList().add(addDrugWorkRequest);
        addDrugWorkRequest.setMessage("Drugs required");
        addDrugWorkRequest.setStatus("Request initiated");
        addDrugWorkRequest.setSender(userAccount);
        addDrugWorkRequest.setRequestDate(new Date());
        addDrugWorkRequest.setDrugItemList(drugItemList);
        addDrugWorkRequest.setPrescription(prescription);

        JOptionPane.showMessageDialog(null, "Request sent succesfully to the pharmacist");

    }//GEN-LAST:event_btnRequestDrugsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestDrugs;
    private javax.swing.JButton btnWishList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox pharmacyJComboBox;
    private javax.swing.JTable requestTable;
    private javax.swing.JTable tblDrugContents;
    // End of variables declaration//GEN-END:variables

}
