/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Patient.Patient;
import Business.Prescription.Diagnosis;
import Business.Prescription.DrugDosages;
import Business.Prescription.DrugItems;
import Business.Prescription.Prescription;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AddDrugWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.ShowDiagnosisHistoryJPanel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private Patient patient;

    private DrugDosages wishListDrugDosage;

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        patient = (Patient) userAccount.getPerson();
        populateDiagnosisHistory();
        wishListDrugDosage = new DrugDosages();

    }

    public void populateDiagnosisHistory() {
        DefaultTableModel dtm = (DefaultTableModel) tblDiagnosisHistory.getModel();
        dtm.setRowCount(0);
        for (Diagnosis d : patient.getDiagnosisHistory().getDiagnosisHistoryList()) {
            Object row[] = new Object[3];
            row[0] = d;
            row[1] = d.getStartDate();
            row[2] = d.getStatus();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiagnosisHistory = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        prescriptionJTable = new javax.swing.JTable();
        btnShowPrescription = new javax.swing.JButton();
        btnBuyDrugs = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnShowRequest = new javax.swing.JButton();
        btnDrugTrack = new javax.swing.JButton();
        btnLowStock = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Patient Work Area JPanel");
        add(jLabel1);
        jLabel1.setBounds(355, 30, 320, 36);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Diagnosis List:");
        add(jLabel2);
        jLabel2.setBounds(100, 73, 150, 23);

        tblDiagnosisHistory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblDiagnosisHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Diagnosis ID", "Start Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDiagnosisHistory);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 99, 685, 162);

        prescriptionJTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        prescriptionJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drugdosage", "Drug Id", "Morning", "Afternoon", "Evening", "Night", "No of days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(prescriptionJTable);
        if (prescriptionJTable.getColumnModel().getColumnCount() > 0) {
            prescriptionJTable.getColumnModel().getColumn(0).setMinWidth(0);
            prescriptionJTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            prescriptionJTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(100, 369, 685, 196);

        btnShowPrescription.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnShowPrescription.setText("Show Prescription");
        btnShowPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPrescriptionActionPerformed(evt);
            }
        });
        add(btnShowPrescription);
        btnShowPrescription.setBounds(810, 100, 280, 40);

        btnBuyDrugs.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBuyDrugs.setText("Buy Drugs");
        btnBuyDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyDrugsActionPerformed(evt);
            }
        });
        add(btnBuyDrugs);
        btnBuyDrugs.setBounds(810, 220, 280, 40);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Dosages List:");
        add(jLabel3);
        jLabel3.setBounds(100, 341, 130, 23);

        btnShowRequest.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnShowRequest.setText("Show Request Status");
        btnShowRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRequestActionPerformed(evt);
            }
        });
        add(btnShowRequest);
        btnShowRequest.setBounds(820, 370, 270, 40);

        btnDrugTrack.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnDrugTrack.setText("Drug Tracking Information");
        btnDrugTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugTrackActionPerformed(evt);
            }
        });
        add(btnDrugTrack);
        btnDrugTrack.setBounds(270, 610, 350, 40);

        btnLowStock.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLowStock.setText("Drugs Low in Stock");
        btnLowStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLowStockActionPerformed(evt);
            }
        });
        add(btnLowStock);
        btnLowStock.setBounds(820, 520, 270, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 2000, 970);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPrescriptionActionPerformed
        // TODO add your handling code here:
        int row = tblDiagnosisHistory.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select an entry form the table", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Diagnosis diagnosis = (Diagnosis) tblDiagnosisHistory.getValueAt(row, 0);
        Prescription prescription = diagnosis.getPrescription();
        DefaultTableModel dtm = (DefaultTableModel) prescriptionJTable.getModel();
        dtm.setRowCount(0);
        for (DrugDosages dd : prescription.getDrugDosagesList()) {
            Object r[] = new Object[7];
            r[0] = dd;
            r[1] = dd.getDrug();
            r[2] = dd.getFrequency().getMorning();
            r[3] = dd.getFrequency().getAfternoon();
            r[4] = dd.getFrequency().getEvening();
            r[5] = dd.getFrequency().getNight();
            r[6] = dd.getNoOfDays();

            dtm.addRow(r);

        }

    }//GEN-LAST:event_btnShowPrescriptionActionPerformed

    private void btnBuyDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyDrugsActionPerformed
        // TODO add your handling code here:
        int row = tblDiagnosisHistory.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select an entry form the table", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Diagnosis diagnosis = (Diagnosis) tblDiagnosisHistory.getValueAt(row, 0);

        if (diagnosis.getStatus().equals("Completed")) {
            JOptionPane.showMessageDialog(null, "The selected diagnosis has been completed. Please select another entry");
            return;
        }
        Prescription prescription = diagnosis.getPrescription();

        BuyDrugsJPanel buyDrugsJPanel = new BuyDrugsJPanel(userProcessContainer, userAccount, enterprise, network, prescription, new AddDrugWorkRequest());
        userProcessContainer.add("buyDrugsJPanel", buyDrugsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnBuyDrugsActionPerformed

    private void btnShowRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRequestActionPerformed
        // TODO add your handling code here:

        DrugsRequestStatusJPanel drugsRequestStatusJPanel = new DrugsRequestStatusJPanel(userProcessContainer, userAccount, enterprise, network);
        userProcessContainer.add("buyDrugsJPanel", drugsRequestStatusJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnShowRequestActionPerformed

    private void btnDrugTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugTrackActionPerformed
        // TODO add your handling code here:

        DrugTrackingJPanel drugTrackingJPanel = new DrugTrackingJPanel(userProcessContainer, patient);
        userProcessContainer.add("drugTrackingJPanel", drugTrackingJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btnDrugTrackActionPerformed

    private void btnLowStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowStockActionPerformed
        // TODO add your handling code here:
        DrugsLowInStockJPanel drugsLowInStockJPanel = new DrugsLowInStockJPanel(userProcessContainer, patient);
        userProcessContainer.add("drugsLowInStockJPanel", drugsLowInStockJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnLowStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyDrugs;
    private javax.swing.JButton btnDrugTrack;
    private javax.swing.JButton btnLowStock;
    private javax.swing.JButton btnShowPrescription;
    private javax.swing.JButton btnShowRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable prescriptionJTable;
    private javax.swing.JTable tblDiagnosisHistory;
    // End of variables declaration//GEN-END:variables

}
