/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierRole;

import Business.Drug.Drug;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class ManageSupplierCatalogJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierOrganization supplierOrganization;
    private UserAccount userAccount;

    /**
     * Creates new form ManageSupplierCatalogJPanel
     */
    public ManageSupplierCatalogJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization supplierOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.supplierOrganization = (SupplierOrganization) supplierOrganization;
        populateDrugs();
    }

    public void populateDrugs() {

        DefaultTableModel dtm = (DefaultTableModel) tblDrugs.getModel();

        dtm.setRowCount(0);
        for (Drug d : supplierOrganization.getDrugCatalog().getDrugCatalog()) {
            Object row[] = new Object[3];
            row[0] = d;
            row[1] = d.getDrugName();
            row[2] = d.getPrice();
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        btnAddDrug = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        txtDrugPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContents = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Supplier Drugs:");
        add(jLabel2);
        jLabel2.setBounds(70, 90, 99, 19);

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugs);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 130, 755, 194);

        btnAddDrug.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddDrug.setText("Add Drugs");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });
        add(btnAddDrug);
        btnAddDrug.setBounds(240, 520, 268, 35);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Drug Name:");
        add(jLabel3);
        jLabel3.setBounds(80, 360, 81, 19);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Drug Price:");
        add(jLabel4);
        jLabel4.setBounds(80, 410, 73, 19);

        txtDrugName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtDrugName);
        txtDrugName.setBounds(240, 350, 268, 35);

        txtDrugPrice.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtDrugPrice);
        txtDrugPrice.setBounds(240, 400, 268, 35);

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 20, 110, 31);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Drug Contents:");
        add(jLabel1);
        jLabel1.setBounds(80, 460, 98, 19);

        txtContents.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        add(txtContents);
        txtContents.setBounds(240, 450, 268, 35);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Manage Supplier Catalog");
        add(jLabel5);
        jLabel5.setBounds(380, 30, 320, 31);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(0, 0, 2030, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:

        String name = txtDrugName.getText();
        int price = 0;
        int contents = 0;

        if (name.equals("") || txtContents.getText().equals("") || txtDrugPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Drug name cannot be kept empty");
            return;
        }
        try {

            price = Integer.parseInt(txtDrugPrice.getText());
            contents = Integer.parseInt(txtContents.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Number only in price and contents fields");
            txtDrugPrice.setText("");
            txtContents.setText("");
            return;

        }

        if (!(supplierOrganization.getDrugCatalog().checkIfDrugNameIsUnique(name))) {
            JOptionPane.showMessageDialog(null, "This drug already exists in the catalog");
            clearFields();
            return;
        }

        Drug d = supplierOrganization.getDrugCatalog().addDrug();
        d.setDrugName(name);
        d.setPrice(price);
        d.setContents(contents);
        JOptionPane.showMessageDialog(null, "Drug has been added succesfully");

        populateDrugs();
        clearFields();

    }//GEN-LAST:event_btnAddDrugActionPerformed

    public void clearFields() {
        txtDrugName.setText("");
        txtDrugPrice.setText("");
        txtContents.setText("");

    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrugs;
    private javax.swing.JTextField txtContents;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtDrugPrice;
    // End of variables declaration//GEN-END:variables

}
