/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplierRole;

import Business.Drug.Drug;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bhavna Menghrajani
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SupplierOrganization supplierOrganization;
    private UserAccount userAccount;

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization supplierOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierOrganization = (SupplierOrganization) supplierOrganization;
        this.userAccount = userAccount;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnWorkRequest = new javax.swing.JButton();
        btnManageCatalog = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Supplier Work Area JPanel");
        add(jLabel1);
        jLabel1.setBounds(420, 40, 320, 49);

        btnWorkRequest.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnWorkRequest.setText("Show Work Request");
        btnWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkRequestActionPerformed(evt);
            }
        });
        add(btnWorkRequest);
        btnWorkRequest.setBounds(450, 250, 268, 50);

        btnManageCatalog.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnManageCatalog.setText("Manage Catalog");
        btnManageCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCatalogActionPerformed(evt);
            }
        });
        add(btnManageCatalog);
        btnManageCatalog.setBounds(450, 150, 268, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1940, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkRequestActionPerformed
        // TODO add your handling code here:

        ManageWorkRequest manageWorkRequest = new ManageWorkRequest(userProcessContainer, userAccount, supplierOrganization);
        userProcessContainer.add("manageWorkRequest", manageWorkRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnWorkRequestActionPerformed

    private void btnManageCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCatalogActionPerformed
        // TODO add your handling code here:
        ManageSupplierCatalogJPanel manageSupplierCatalogJPanel = new ManageSupplierCatalogJPanel(userProcessContainer, userAccount, supplierOrganization);
        userProcessContainer.add("manageSupplierCatalogJPanel", manageSupplierCatalogJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCatalog;
    private javax.swing.JButton btnWorkRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
